### ISSUE TITLE
PLEASE SOMEBODY HELP TO FIND THE PASSWORD AND AID OF THE admin and user while running the program

### ISSUE THREAD

**Issue by KES2619** [anpct/billingsystem#1] opened 2020-12-07 16:38 UTC

**Comment by anpct** [comment] 2020-12-07 21:30
Run createdb.py with your database details, it will automatically create a table called ADMIN_DETAILS.
Insert a row into this table manually with the details of the admin:
`INSERT INTO ADMIN_DETAILS VALUES(1, "name", "password", 1234567891);`

**Comment by KES2619** [comment] 2020-12-08 03:57
> Run createdb.py with your database details, it will automatically create a table called ADMIN_DETAILS.
> Insert a row into this table manually with the details of the admin:
> `INSERT INTO ADMIN_DETAILS VALUES(1, "name", "password", 1234567891);`

thankyou so much but i have one more error now
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\user\Desktop\main.py", line 551, in <lambda>
    sb= Button(al, text= "LOGIN", fg="white", bg="#1966ff", command= lambda: admin_auth(e1.get(),e2.get()))
  File "C:\Users\user\Desktop\main.py", line 516, in admin_auth
    ad(username)
  File "C:\Users\user\Desktop\main.py", line 486, in ad
    t9 = change_price_of_item(tab_main, username)
  File "C:\Users\user\Desktop\main.py", line 98, in change_price_of_item
    clicked.set(options[0])
IndexError: list index out of range
can you help me?

**Comment by KES2619** [comment] 2020-12-08 04:01
thanks a lot but i have one more error now plse help
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1883, in
__call__
    return self.func(*args)
  File "C:\Users\user\Desktop\main.py", line 551, in <lambda>
    sb= Button(al, text= "LOGIN", fg="white", bg="#1966ff", command=
lambda: admin_auth(e1.get(),e2.get()))
  File "C:\Users\user\Desktop\main.py", line 516, in admin_auth
    ad(username)
  File "C:\Users\user\Desktop\main.py", line 486, in ad
    t9 = change_price_of_item(tab_main, username)
  File "C:\Users\user\Desktop\main.py", line 98, in change_price_of_item
    clicked.set(options[0])
IndexError: list index out of range

**Comment by anpct** [comment] 2020-12-08 05:58
Duplicate of #2

**Closed as completed by anpct** 2020-12-08 05:58 UTC

**Comment by jaspinder21** [comment] 2022-05-18 08:42
Please somebody help me to find user login also the sales column is going blank in admin section because of that deleted bill is not showing nor the sales.
